project:
  type: book
# always_allow_html: yes
# always_allow_html: true
# prefer-html: true

execute:
  freeze: auto

book:
  title: "The cost of a gaff in Ireland"
  author: "Des"
  date: "10/29/2022"
  chapters:
    - index.qmd
    #- 2_clean.qmd
    - testing.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


